# Generated by Django 5.2 on 2025-07-10 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='aperitivos',
            field=models.ManyToManyField(blank=True, to='negocio.aperitivo'),
        ),
    ]
