# Generated by Django 5.2 on 2025-07-10 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0002_cita_aperitivos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='email',
        ),
    ]
